#!/usr/bin/env bash
#install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee index.nginx-debian.html
sudo /etc/init.d/nginx restart
