#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get -y install haproxy=1.8.\*
cat >> /etc/haproxy/haproxy.cfg << EOL
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    mode http
    server 1631-web-01 35.237.26.128:80 check
    server 1631-web-02 3.92.66.113:80 check
EOL
sudo service haproxy restart
