#!/usr/bin/env bash
# code for fun!

file='/var/run/holbertonscript.pid'
touch $file
echo $$ > $file

function signalquit() {
	trap 'rm $file && exit'
}

trap 'echo I hate the kill command && rm $file && exit' SIGTERM
trap "echo Y U no love me?! && exit" SIGINT
trap signalquit SIGQUIT

let i=1
while [ $i ]; do
	echo "To infinity and beyond"
	sleep 2
done

