#!/usr/bin/env bash
# FizzBuzz bash version

let i=0
while [ $i -le 100 ]; do
	if [[ $((i%5)) == 0 && $((i%3)) == 0 ]]; then
		echo "FizzBuzz"
	elif [ $((i%3)) == 0 ]; then
		echo "Fizz"
	elif [ $((i%5)) == 0 ]; then
		echo "Buzz"
	else
		echo $i
	fi
	let i=i+1
done

