#!/usr/bin/env bash
# Information about a file

FILE="holbertonschool"
if [ -e ./$FILE ]; then
	echo "$FILE file exists"
	if [ ! -s ./$FILE ]; then
		echo "$FILE file is empty"
	else
		echo "$FILE file is not empty"
	fi
	if [ -f ./$FILE ]; then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi

